### ISSUE TITLE
Loader: add support for {{rootURL}}

### ISSUE THREAD

**Issue by jonasbuechel** [ivanvotti/ember-svg-jar#25] opened 2017-01-04 07:48 UTC
The loader assumes a rootURL of '/'. 
If I run the app in a subfolder like rootURL: '/my-subfolder/' the loader calls the file in '/assets/svg/symbol/symbols.svg' and runs into an HTTP Error 403.

Is there an option to overwrite the loader path?

My configuration: 

`
svgJar: {
      strategy: ['symbol', 'inline'],

      symbol: {
        sourceDirs: ['svgs', 'public/assets/svg/symbol'],
        outputFile: '/assets/svg/symbol/symbols.svg',
        includeLoader: true
      },

      inline: {
        sourceDirs: ['svgs', 'public/assets/svg/inline']
      }
    }
`

**Comment by jonasbuechel** [comment] 2017-01-04 10:15
I temporary fixed my issue by adding the loader to the index.html like this: 

`<script>
      var ajax = new XMLHttpRequest();
      ajax.open('GET', '{{rootURL}}assets/svg/symbol/symbols.svg', true);
      ajax.send();
      ajax.onload = function(e) {
        var div = document.createElement('div');
        div.innerHTML = ajax.responseText;
        document.body.insertBefore(div, document.body.childNodes[0]);
      };
    </script>`

**Comment by alexnj** [comment] 2017-04-24 02:30
Duplicate of #22

**Comment by ivanvotti** [comment] 2017-05-12 12:56
The issue is fixed. I'll release today.

**Closed by ivanvotti** 2017-05-12 12:56 UTC
